name: think_dock_mobile
description: "think dock mobile project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  google_mobile_ads: ^5.3.1  # ✅ 이걸로 변경

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/icon/ship.png
    - assets/splash/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/ship.png

flutter_native_splash:
  image: assets/splash/logo.png
  color: "#ffffff"
  android: true
  ios: true
